In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
print(X_train)

[[0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.

In [11]:
ones = np.ones((X_train.shape[0], 1))
X_train = np.concatenate((ones, X_train), axis=1)
print(X_train)

[[1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 542.05 51743.15 0.0]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 1.0 1.0 1.0 1.0 1.0 0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 1.0 1.0 1.0 1.0 1.0 1.0 0.0 0.0 23640.93 96189.63 1480

In [ ]:
zeros = np.zeros((X_train.shape[1],1))
def derived_cost_function_b(w, b):
  sum = 0
  for i in range(len(X_train)):
    sum = sum + (w @ X_train[i] + b - y_train[i])
  sum = sum/len(X_train)
  return sum
def derived_cost_function_w(w, b):
  sum = np.mean(X_train.T  @ (w * X_train - y_train))
  return sum
